name: prueba-tecnica-diego-garcia

services:
  postgres:
    image: postgres:17-alpine
    container_name: prueba-tecnica-diego-garcia-postgres
    environment:
      POSTGRES_DB: prueba-tecnica-diego-garcia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - prueba-tecnica-diego-garcia_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  prueba-tecnica-diego-garcia_postgres_data: